### ISSUE TITLE
Return by parameter and type checks on a null initialized variable #3227

### ISSUE THREAD

**Issue by ktomk** [psalm/psalm-github-bot#128]
some message here w/o a link.

/e1:  bot notified me, clicked the link to "can you reproduce" and edited in a link:

https://psalm.dev/r/a8b6fc3de1

**Comment by ktomk** [comment]
Bot changes the comment after /e1. 

Link is: https://psalm.dev/r/a8b6fc3de1

**Comment by ktomk** [comment]
Bot re-posts the link being happy to find the snipped (again).

**Comment by ktomk** [comment]
> Bot changes the comment after /e1.
> 
> Link is: https://psalm.dev/r/a8b6fc3de1

let's also quote reply with the quote containing the same link again.

**Comment by weirdan** [comment]
So basically there are two issues:
1. Request to reproduce is removed on first edit, and the comment is not monitored anymore. Instead, it should be left in place until the comment is edited to either contain a reference to psalm.dev (such as 'Could not reproduce on psalm.dev', then the request is to be removed) or a link to a snippet (in which case it's to be resolved and should continued to be monitored, in case it changes again).
2. Links in blockquotes should not be resolved. General observation: relatively few people use quotes on Github, but those who do - use them a lot.

**Comment by ktomk** [comment]
for 1.:

this did work I would say. it was just that later on the bot continued to talk about the same link again and again (a bad robot you are).

just an idea: what about if the bot keeps note if the specific psalm.dev URI has been already mentioned in an earlier bot comment on that issue, it does not comment about it again. This would immunize against quotes and perhaps other concurrency problems.

or: instead of adding a new comment, just refer to it's earlier one and see if the URI has been already processed and if so, do not add another comment, and if not, add a new comment with the new / additinal URI.

I like the feature btw. that it is possible to unfold the link entry and see the example directly on Github.

**Comment by ktomk** [comment]
staled.
