### ISSUE TITLE
Comment edited to remove links

### ISSUE THREAD

**Issue by AndrolGenhald** [psalm/psalm-github-bot#533]
https://github.com/vimeo/psalm/issues/7424#issuecomment-1016537772
The 3 dot menu on that comment says "Sorry, something went wrong."

I think the comment should be hidden if the referenced comment is edited to remove all of the psalm.dev links, though I'm not sure if it can be hidden so that it doesn't show up at all, and if the comment is edited again to include links it should show up again.

If github doesn't allow hiding and unhiding bot comments the bot should at least handle the case where an edit removes links gracefully and say "No snippets found" or something.

Edit: Looks like it actually does remove the comment, but only after a page refresh. I'm guessing that's a limitation on GitHub's end though, so I guess this is a non-issue. The comment doesn't reappear after editing to include psalm.dev links again, but that's probably not a big deal.

**Comment by weirdan** [comment]
> The comment doesn't reappear after editing to include psalm.dev links again, but that's probably not a big deal.

Once the comment is removed the bot doesn't have a place to add links to. I didn't want to end up in a situation where there are multiple comments in between the comment and the bot response.

**Comment by AndrolGenhald** [comment]
> Once the comment is removed the bot doesn't have a place to add links to. I didn't want to end up in a situation where there are multiple comments in between the comment and the bot response.

That's what I figured. It might be worth considering leaving it there with "No snippets" instead of removing it, but it's probably not something that happens often enough to be worth it. I'm happy with it removing it entirely now that I know it works once the page is refreshed.
