### ISSUE TITLE
Handle tabs in code better

### ISSUE THREAD

**Issue by AndrolGenhald** [psalm/psalm-github-bot#541]
The editor at psalm.dev uses width 4 for tabs, the comment from the bot should either do the same, or if that's not possible, expand tabs to 4 spaces so the indentation at least looks the same.

**Comment by weirdan** [comment]
Example: https://psalm.dev/r/81669fb682

**Comment by weirdan** [comment]
I actually think this would be better handled on the psalm.dev's side, by tweaking the editor: https://github.com/codemirror/CodeMirror/issues/988
