### ISSUE TITLE
Link parser includes closing parenthesis in link

### ISSUE THREAD

**Issue by AndrolGenhald** [psalm/psalm-github-bot#544]
See [here](https://github.com/vimeo/psalm/pull/7590#issuecomment-1030633051). The bot seems to have included the closing parenthesis from the markdown link syntax in the link itself. I'm not sure why it does it only when using the `php=` feature, maybe it's not actually the parser and it's something else?

**Comment by weirdan** [comment]
(https://psalm.dev/r/265ca1743a?php=7.4)
