### ISSUE TITLE
Free Heroku hosting is being phased out

### ISSUE THREAD

**Issue by weirdan** [psalm/psalm-github-bot#658]
Got this today:

> Dear Customer,
>
> Thank you for being a Heroku user. Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available. You can learn more about these and other important changes from our GM, Bob Wise, on the [Heroku blog](https://hello.heroku.com/e/36622/next-chapter/m49jdm/1140555300?h=OE06kmPe4Nb9cym8AS7ekH2GznAk-GWUKOWTwjlIh-E).
>
> Existing free dynos and Heroku data add-ons will be impacted, so action by you is required. To prevent any disruption to your apps or data using free plans, you will need to upgrade from a free plan to a paid plan before November 28, 2022.
>
> For instructions on how to upgrade and for other questions, please [visit our FAQ.](https://hello.heroku.com/e/36622/-heroku-free-product-plans-faq/m49jdq/1140555300?h=OE06kmPe4Nb9cym8AS7ekH2GznAk-GWUKOWTwjlIh-E)
>
> Thank you,
>
> The Heroku Team

**Comment by weirdan** [comment]
Currently it serves ~30 requests per day.

**Comment by weirdan** [comment]
So it's probably quite affordable to go serverless in this case.

**Comment by weirdan** [comment]
Got it running on Google Cloud functions: https://github.com/psalm/psalm-github-bot/issues/6#issuecomment-1264235367

**Comment by weirdan** [comment]
The Google Cloud function deployment and hosting work fine.

**Comment by weirdan** [comment]
@orklah @muglug there's a new github application available: https://github.com/apps/psalm-github-bot-beta, currently installed in this repo only, in addition to the regular bot. We should test it and then replace update the primary bot settings with to use the function running on GCF.

**Comment by weirdan** [comment]
This comment should be picked up by both bots.

https://psalm.dev/r/4121eceef8

**Comment by orklah** [comment]
seems to work fine! What should we do to install it?

**Comment by weirdan** [comment]
1. There's no rush, the Heroku-hosted bot should work fine until Nov 28.
2. I think when the time comes I would just replace github app settings for the current bot with the settings for the new one, so no reinstallation would be necessary. However, if I'm not available at that time you could just uninstall the old one and install the new one:
   * Navigate to https://github.com/apps/psalm-github-bot-beta
   * Click `Configure`
   * In `Repository access` section, select the repositories you need
   * Navigate to https://github.com/apps/psalm-github-bot
   * Click `Configure`
   * Click `Uninstall`

**Comment by weirdan** [comment]
Installation in `vimeo/psalm` repo may require admin access, so you may need to contact @muglug

**Comment by weirdan** [comment]
@psalm-github-bot (production version) now runs on GCF.

@orklah you don't need to install beta bot, nor you can as I deleted it.
